lib/graphism.ex
[BT-NNNN]
When definiing an action spec, eg:
```
create(produces: :custom_type, using: SomeCustomModule)
```
the `:produces` option is no longer mandatory. If not specified, the mutation will return the entity itself.
=> Optional :produces in action specs

CHANGELOG.md, README.md, lib/graphism.ex, test/key_test.exs, test/support/case.ex
Completes composite key support to Graphism.
This feature was partially implemented. Now we also support it for keys based on relations.
```elixir
entity :user do
unique(string(:name))
end
entity :organisation do 
unique(string(:name))
end
entity :membership do
belongs_to(:user)
belongs_to(:organisation)
key([:user, :organisation]) # <-- composite key
action(:read)
end
```
=> Composite keys

CHANGELOG.md, lib/graphism.ex, lib/migrations.ex
Implements graceful handling of foreign key constraints, by adding to the create changesets.
This is a bit tricky to test without a proper database and a migrated schema.
=> Graceful foreign key constraint validations

CHANGELOG.md, lib/graphism.ex
This change allows for a more flexible policy when fetching an entity after creating or updating it via the Elixir api.
Specifically, all supported preloads options from the `get_by_id` api functions are now also supported when mutating existing entities.
=> More flexible entity fetch on api create/update

CHANGELOG.md, lib/graphism.ex
Adds the ability to chain after hooks, by not discarding the output from one hook, so that it can be used as the input for the next one.
=> Ability to chain after hooks

CHANGELOG.md, lib/graphism.ex
Support for computed optional attributes, eg when we do:
```
optional(string(:user_id), from_context: [:user])
```
then take into consideration that the `:id` property might be null.
=> Support optional computed attributes

CHANGELOG.md, README.md, lib/graphism.ex
Adds the ability to "nest" entities in order to build recursive, tree-like data structures:
```elixir
entity :node do
maybe(belongs_to(:node, as: :parent)
end
```
=> Self referencing entities

CHANGELOG.md, mix.exs
Release v0.3.3:
* Self referencing entities - [#65](https://github.com/Gravity-Core/graphism/pull/65)
=> Release 0.3.3

CHANGELOG.md, lib/migrations.ex
More robust migration parsing. Allows for extra directives that might not be supported by graphs to be present in migration files, eg: `@disable_ddl_transaction true`
=> More robust migration parsing

CHANGELOG.md, README.md, lib/graphism.ex
This feature is useful when we have fields that might be optional at the api level, but we still need to ensure that non-empty values will always be stored in the database:
```elixir
entity :file do
optional(non_empty(string(:name)))
end
```
This will allow us to customise the value of `name` while ensuring non-blank values will ever hit the database.
=> Non empty fields

CHANGELOG.md, lib/graphism.ex
Support for `virtual` syntax sugar:
```elixir
entity :token do
...
virtual(integer(:expires))
...
end
```
=> Virtual syntax sugar

CHANGELOG.md, README.md, lib/migrations.ex
Adds the ability to tell Graphism to skip migrations: 
```
defmodule My.Custom.Migration do
use Ecto.Migration
@graphism [:skip] # add the :skip option
def up do
execute("...")
end
end
```
=> Skippable migrations

CHANGELOG.md, README.md, lib/graphism.ex
Adds sorting and paginating capabilities to all GraphQL queries. Eg:
```elixir
entity :contact do
string(:first_name)
string(:last_name)
action(:list)
end
```
You can query all your contacts by chunks:
```
query {
contacts {
all(sortBy: "lastName", sortDirection: ASC, limit: 20, offset: 40) {
firstName,
lastName
}
}
}
```
=> Sorting and paginating queries

CHANGELOG.md, README.md, lib/graphism.ex
Use `aggregateAll` instead of `aggregate` as the query name, for better consistency with `list` queries.
=> Use aggregateAll instead of aggregate

CHANGELOG.md, lib/graphism.ex
More accurate definition of primary keys in schemas, when dealing with parent-children relations with aliases. With this, Graphism will always explicitly say which is the primary key column, supporting the special use case of relations with aliases.
=> More accurate primary keys in relations with aliases

CHANGELOG.md, lib/migrations.ex
Use a better ordering in migrations. For example, if we are renaming an enum, create the new enum first, use it in ables, then drop the old enum.
=> Better migrations

CHANGELOG.md, README.md, lib/migrations.ex
Adds support for cascade deletes in Graphism. This can be defined on a per relation basis:
```elixir
entity :node do
belongs_to(:node, as: parent, delete: :cascade)
end
```
=> Cascade deletes

CHANGELOG.md, lib/graphism.ex
An internal improvement so that we also have access to parent structs (not just their ids) in before hooks.
=> Pass parent structs to before hooks

CHANGELOG.md, lib/graphism.ex
Adds a couple of introspection enhancements:
* A more robust `column_name/1` function so that we can easily resolve a entity field into a column, in different contexts.
* The graphism context is now enriched with the schema module of the entities involved in the current context. If we are evaluating a relationship field between two entities, the context will contain both source and the target entity schemas.
=> Introspection enhancements

CHANGELOG.md, lib/graphism.ex, lib/migrations.ex
Supports long strings of text: 
```elixir
entity :article do
text(:content)
end
```
At the api level, these will be strings. But in Postgres, they will be stored as `TEXT`, with no particular validation on the length of the string.
=> Add :text attribute type

CHANGELOG.md, lib/migrations.ex, mix.exs
Fixes support for the new `:text` attribute type, which was partially broken in its first release.
=> Fix support for text attributes

CHANGELOG.md, lib/graphism.ex
This is a significant change that moves towards manual preloads, rather than Graphism trying to be too smart. As part of this:
* `ContextBuilder` is no longer needed. This convenient, but also a bit of a code smell, and it is good that is now gone.
* A new  `paths_to/1` has been added to each schema module. This allows to perform hierarchy discovery:
```elixir
iex> MySchema.Post.paths_to(:user)
[[:user], [:blog, :user]]
```
=> Manual preloads

CHANGELOG.md, README.md, lib/graphism.ex
Adds telemetry events for external authorisation calls:
* `[:graphism, :allow, :stop]`
* `[:graphism, :scope, :stop]`
Measurement is given by `:duration` and metadata has keys: `:entity`, `:kind`, and `:value`.
=> Authorization telemetry

CHANGELOG.md, lib/graphism/resolver.ex
Better support for aliases in computed relations. 
Eg:
```elixir
entity :blog do
... 
belongs_to(:user, as: :owner)
...
end
entity :post do
...
belongs_to(:blog, as: :parent)
belongs_to(:user, as: :author, from: [:parent, :owner])
...
end
```
=> Better support for aliases in computed relations

CHANGELOG.md, README.md, lib/graphism.ex
Makes field level authorization optional:
```elixir
def module MySchema do
use Graphism, repo: MyRepo, field_auth: false
end
```
=> Optional field auth

CHANGELOG.md, lib/graphism/querying.ex
Fixes the way relations are cache, when evaluating dot expressions. Rather than caching by entity/relation, we should be caching by id/relation, otherwise undesired side effects are to be expected!
=> Cache relations properly

CHANGELOG.md, lib/graphism/schema.ex
Do not add a binding to a query if it already exists.
=> Safer aliasing in queries

CHANGELOG.md, lib/graphism/schema.ex
Support for not nil schema filters.
```elixir
q = from p in Post, as: :post
Blog.Schema.filter(Post, [:comments], :neq, nil, q, :post)
```
=> Not nil schema filter

CHANGELOG.md, lib/graphism/policy.ex, mix.exs
Supports expressions in the form:
```
scope property_unset do
some_property == nil
end
```
where we can test against `nil`.
=> Allow nil comparison in scopes

CHANGELOG.md, lib/graphism/policy.ex, mix.exs
Supports the `!=` operator in scope expressions. Eg:
```elixir
scope :is_leaf do
parent != nil
end
```
=> Not-equal comparison syntax sugar

CHANGELOG.md, lib/graphism/querying.ex, mix.exs
The :neq operator was not properly supported in the comparator api.
=> Better support for :neq in comparisons

CHANGELOG.md, README.md, lib/migrations.ex
Adds support for this notation:
```elixir
entity :node do
...
maybe_belongs_to(:node, as: parent, delete: :set_nil)
...
end
```
which translates into a `on_delete: :nilify_all` in the generated ecto migration.
=> Set nil on parent deletes

CHANGELOG.md, lib/graphism/auth.ex
Adds debug logging to the policy evaluations. Sometimes it might be tricky to understand why a scope is allowing or denying access. This should make it easier troubleshoot things. In your `config.exs`, turn this feature on:
```elixir
config :graphism,
debug: true,  # <- set this to true
schema:  ...
```
Configure your log level so that `debug` is enabled too. Then you should start seeing log entries such as: 
```
[debug] graphism policy allow: [
paths: [:node, :parent],
context: %{
analytic: %{user: %{roles: [:anonymous]}},
args: %{name: "notion"},
node: %AnalyticWeb.Schema.Node{
__meta__: #Ecto.Schema.Metadata<:loaded, "nodes">,
id: "ae98f531-6d0f-4ffb-b4a1-b9168cc69d49",
name: "notion",
parent_id: "61d67aa4-7e0d-4630-8058-d82ce80fa15f",
parent: #Ecto.Association.NotLoaded<association …
```
=> Policy evaluation debug logs

CHANGELOG.md, lib/graphism/graphql.ex, mix.exs
Generates input types for inlined children creations in a slightly smarter way, by only skipping those relations that have the same name as the parent entity. Other relations, which might be aliased, are left in the input type.
=> Smarter inline mutation input types

CHANGELOG.md, lib/graphism/auth.ex, mix.exs
It seems we are still getting truncated output when debugging auth policies
=> Workaround truncated auth debug

CHANGELOG.md, lib/graphism/auth.ex, mix.exs
Supports @ notations in scopes
```elixir
scope :not_internal_channel_tag do
"@.tag.internal" == false
end
```
=> Support for @ notation in scopes

CHANGELOG.md, lib/graphism/schema.ex, mix.exs
When generating schema filters, and testing for non nil values, the generated where clause was using a syntax that is not supported by ecto, which raises the following error:
```
** (ArgumentError) comparison with nil is forbidden as it is unsafe. If you want to check if a value is nil, use is_nil/1 instead
(ecto 3.9.1) lib/ecto/query/builder.ex:1030: Ecto.Query.Builder.not_nil!/1
(analytic 0.1.0) lib/analytic_web/schema/schema.ex:1: AnalyticWeb.Schema.Database.filter/5
```
=> Fix ecto syntax for non nil values in schemas filters

CHANGELOG.md, lib/graphism.ex, lib/graphism/entity.ex, mix.exs
Adds support for the time datatype. This seems to be a native type in both postgres and graphql, so the implementation here is quite trivial.
=> Add support for the Time datatype

CHANGELOG.md, README.md, lib/graphism/entity.ex, lib/graphism/resolver.ex
Improves support for computed attributes and relations. Computed relations where not being supported explicitly.
Now it is possible to add a `:using` hook to the field itself.
=> Improved support for computed fields

CHANGELOG.md, README.md, lib/graphism.ex, lib/graphism/api.ex, lib/graphism/entity.ex, lib/graphism/schema.ex
Support for bigint attributes
```elixir
entity :my_app  do
bigint(:active_users)
end
```
In reality, bigint is just a database concept, so this attribute type will be seen as a plain integer in GraphQL and Elixir. However database migrations will create the postgres' `bigint` type
=> Bigint attributes

CHANGELOG.md, README.md, lib/graphism/entity.ex
Adds support for the `inverse:` keyword in `belongs_to` and `has_many` relations, so that Graphism is able to better identify what the inverse relation is in order to build the ecto schema more accurately.
=> Explicit inverse relations
