Otion-Core/graphism

- lib/graphism.ex
[BT-NNNN]
Better plurals with Inflex. Eg `quiz` automagically becomes `quizzes`.
> fix(schema): use Inflex for pluralization

- lib/migrations.ex
[BT-NNNN]
Small fixes when creating a migration graph
> fix(migrations): better migration graph

- lib/graphism.ex
[BT-126]
This PR moves the generation of uuids from the client to the server.
[BT-126]: https://bite-core.atlassian.net/browse/BT-126
> fix(resolvers): server side uuids

- lib/graphism.ex
[BT-NNNN]
Implements nested queries and mutations
> feat(graphql): nested queries and mutations

- lib/error_middleware.ex
- lib/graphism.ex
[BT-NNNN]
This PR improves how graphql errors are reported.
Also implements :readonly attributes, eg:
```
attribute(:verified, :boolean, default: false, modifiers: [:readonly])
```
> Improved GraphQL errors and readonly fields

- lib/graphism.ex
[BT-NNNN]
Readonly attributes were still part of the ecto changesets. So it was not really possible to create an entity that contained readonly fields. This PR fixes this.
> fix(schema): remove readonly attributes from ecto changesets

- lib/graphism.ex
- lib/migrations.ex
[BT-NNNN]
This PR adds a few major features:
* support for virtual entities (non stored)
* support for internal entities and attributes (non exposed via graphql)
* support for restricted and custom actions
* support for argument transformers
> feat(schema): added virtual, internal, transforms and custom actions

- lib/graphism.ex
> fix(schema): fix parsing actions

- lib/error_middleware.ex
- lib/graphism.ex
[BT-NNNN]
Attribute modifier `secret` is now `writeonly`.
Also fixed graphql errors fields to be camelcase.
> Renamed secret modifier

- README.md
[BT-NNNN]
Just some documentation changes with the list of supported modifiers so far.
> Modifier docs

- lib/graphism.ex
[BT-NNNN]
This PR implements a simple auth middleware:
```
entity :super_user do
...
update(allow: Analytic.User.Self)
end
```
> Auth middleware

- lib/graphism.ex
[BT-NNNN]
Fixes the implementation of transformed attributes, which was totally broken :)
> fix(transforms): fix call to attribute transforms

- README.md
- lib/graphism.ex
[BT-NNNN]
This PR brings the following improvements:
* New `computed` (was readonly) and `private` (writeonly) modifiers 
* Removed attribute `transform` option
* Added `before` create & update hooks.
> fix(refactor): new computed & private modifiers

- README.md
My OCD forced me to do that. 😕
> chore(readme): add emoji after the schema modifiers heading

- lib/graphism.ex
- lib/migrations.ex
[BT-NNNN]
Better implementation for enums and Postgres types.
> fix: improved enums management

- CHANGELOG.md
- lib/graphism.ex
Optional preloads.
Adds an api option to skip default preloads.
> Optional preloads

- CHANGELOG.md
- lib/graphism.ex
- test/date_test.exs
Support for dates:
```elixir
entity :user do
date(:birthdate)
end
```
> Support for dates without time information

- CHANGELOG.md
- mix.exs
> Release v0.2.0

- CHANGELOG.md
- mix.exs
> Release v0.2.1

- CHANGELOG.md
- lib/graphism.ex
- lib/migrations.ex
Supports non unique keys:
```elixir
entity :search do
string(:type)
datetime(:created_at)
... 
key([:type, :created_at], unique: false)
end
```
> Non unique keys

- CHANGELOG.md
- mix.exs
> Release v0.2.2

- CHANGELOG.md
- lib/graphism.ex
- lib/migrations.ex
Adds a new `:upload` type for file uploads.
> File uploads

- CHANGELOG.md
- mix.exs
Release Graphism 0.3.0
Features:
* File uploads (#59)
> Release v0.3.0

- CHANGELOG.md
- mix.exs
Release v0.3.1 with a single change:
* #61
> Release v0.3.1

- CHANGELOG.md
- README.md
- lib/graphism.ex
Adds support for custom Absinthe middleware:
```
use Graphism, repo: ..., middleware: [My.Middleware]
```
> Absinthe middleware

- CHANGELOG.md
- mix.exs
Changes:
* Add support for Absinthe middleware (#63)
> Release 0.3.2

- CHANGELOG.md
- README.md
- lib/graphism.ex
Improvements when listing entities:
* Default entity sort
* Include preloaded children
> Entity sort

- CHANGELOG.md
- mix.exs
Release 0.3.4:
* Entity sort - #67
> Release v0.3.4

- CHANGELOG.md
- mix.exs
> Release 0.3.5

- CHANGELOG.md
- mix.exs
Release v0.3.6 with a single fix
#72
> Release v0.3.6

- CHANGELOG.md
- README.md
- lib/graphism.ex
- mix.exs
Release 0.3.7.
Adds immutable fields:
```elixir
entity :file do
immutable(upload(:content))
end
```
> Release v0.3.7

- CHANGELOG.md
- mix.exs
Release v0.3.8:
* Non empty fields - [#75](https://github.com/Gravity-Core/graphism/pull/75)
> Release v0.3.8

- CHANGELOG.md
- lib/graphism.ex
A couple of improvements when validating fields:
* For relations, treat empty string the same as nil.
* For string attributes, validate length and return a proper graphql error rather than crashing
> Field validation improvements

- CHANGELOG.md
- mix.exs
Changes in this release:
* https://github.com/Gravity-Core/graphism/pull/77
> Release 0.3.9

- CHANGELOG.md
- mix.exs
> Release 0.3.10

- CHANGELOG.md
- mix.exs
> Release v0.4.0

- CHANGELOG.md
- README.md
- lib/graphism.ex
Adds simple aggregate queries to Graphism:
```
query {
posts {
aggregate {
count
}
}
}
```
> Aggregate queries

- CHANGELOG.md
- lib/graphism.ex
- mix.exs
Fixes the code around pagination, sorting and adding preloads into queries.
> Fix query pagination and preloads

- CHANGELOG.md
- lib/graphism.ex
- mix.exs
Allows for `offset` and `limit` to be set independently.
> More flexible query pagination

- CHANGELOG.md
- mix.exs
> Release 0.4.4

- CHANGELOG.md
- lib/graphism.ex
Adds a `column_type/1` function to each entity schema module.
> Add schema column_type/1

- CHANGELOG.md
- README.md
- lib/graphism.ex
Replaces functions `column_name/1` and `column_type/1` by a new single `field_spec/1` function that works for attributes and relations.
> Improved schema introspection

- CHANGELOG.md
- lib/graphism.ex
Scopes results obtained from list queries, and filters out those that are not allowed.
> Scope list results

- CHANGELOG.md
- lib/graphism.ex
Slims down the amount of preloads.
> Optimized preloads

- CHANGELOG.md
- lib/graphism.ex
By default, do not refetch entities after creating/updating them
> Optional entity refetch

- CHANGELOG.md
- README.md
- lib/graphism.ex
Adds support for custom queries
> Custom queries

- CHANGELOG.md
- README.md
- lib/graphism.ex
Instruments calls to `relation/2` in api modules.
> Relation telemetry

- CHANGELOG.md
- lib/migrations.ex
> Fix index creation order

- CHANGELOG.md
- mix.exs
> Release v0.7.0

- CHANGELOG.md
- lib/graphism/graphql.ex
Simplifications around authorisation on children/has_many relations
> Simplified auth on has_many relations

- CHANGELOG.md
- README.md
- lib/migrations.ex
Small fix that makes migrating constraints a bit more reliable.
Also improved docs.
> More robust constraint migrations

- CHANGELOG.md
- README.md
Improves docs by adding a step-by-step Getting started guide
> Getting started guide

- CHANGELOG.md
- lib/graphism/ast.ex
- lib/graphism/resolver.ex
Better rendering of AST variables, so that the macros being generated are a bit more hygienic.
> Ast improvements

- CHANGELOG.md
- mix.exs
> Release v0.7.3

- CHANGELOG.md
- lib/graphism/openapi.ex
- lib/graphism/route.ex
Some small improvements and fixes around Openapi spec generation:
* Better tags for some routes
* Fix the route for read by unique key operations.
> Openapi improvements

- CHANGELOG.md
- lib/graphism.ex
- lib/graphism/api.ex
- lib/graphism/entity.ex
- lib/graphism/graphql.ex
- lib/graphism/hooks.ex
- lib/graphism/resolver.ex
- lib/graphism/rest.ex
* Makes the schema auth hook completely optional now.
* Also brings some improvements that produce dialyzer-friendlier code when an entity does not have any relations.
> Optional auth

- CHANGELOG.md
- lib/graphism.ex
- lib/graphism/entity.ex
- lib/graphism/graphql.ex
Adds support for list arguments in custom actions:
```elixir
action(:block, using: User.BlockUsers, args: [ids: {:list, :id}])
```
> List arguments in custom actions

- CHANGELOG.md
- lib/migrations.ex
> Drop tables after indices

- CHANGELOG.md
- lib/graphism/auth.ex
My trial of fixing the issue we're facing when combining multiple scopes.
> Invert the order when combining queries using intersect

- CHANGELOG.md
- lib/graphism/api.ex
- lib/graphism/entity.ex
- test/virtual_test.exs
Passes the context map from the GraphQL layer to the api layer, and down to the hook `execute` functions.
> Pass context to api functions

- CHANGELOG.md
- mix.exs
> Release v0.14.0

- CHANGELOG.md
- README.md
- lib/graphism/api.ex
- lib/graphism/entity.ex
- lib/graphism/graphql.ex
- lib/graphism/resolver.ex
- lib/graphism/schema.ex
- lib/migrations.ex
Similar to #154  but now also for relations
> Virtual relations

- CHANGELOG.md
- mix.exs
> Release v0.15.0

- CHANGELOG.md
- mix.exs
Bump version and update changelog
> Release v0.16.1

- CHANGELOG.md
- README.md
- lib/graphism.ex
- lib/graphism/dataloader.ex
- lib/graphism/entity.ex
- lib/graphism/schema.ex
- lib/graphism/through.ex
Adds support for `has_many` relations using the `through` notation from Ecto.
> Through has many relations

- CHANGELOG.md
- mix.exs
Release 0.16.2 with the `:through` relationships as the only new feature.
> Release 0.16.2
